# Generated by Django 3.0.6 on 2020-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
